typhoon-blade-1.1.1

diff --git a/blade b/blade
--- a/blade
+++ b/blade
@@ -15,20 +15,21 @@
 #        DATE:    Dec 17 2011
 #        BY  :    Michaelpeng
 #        MODIFICATION: Created
+BLADE_AUTO_UPGRADE="no"
 
 function _info()
 {
     if [ -t 1 ]; then
-        echo -e "\e[1;36mBlade(info): $@\e[m"
+        echo -e "\033[1;36mBlade(info): $@\033[m" >&2
     else
-        echo -e "Blade(info): $@"
+        echo -e "Blade(info): $@" >&2
     fi
 }
 
 function _warning()
 {
     if [ -t 2 ]; then
-        echo -e "\e[1;33mBlade(warning): $@\e[m" >&2
+        echo -e "\033[1;33mBlade(warning): $@\033[m" >&2
     else
         echo -e "Blade(warning): $@" >&2
     fi
@@ -37,37 +38,65 @@ function _warning()
 function _error_exit()
 {
     if [ -t 2 ]; then
-        echo -e "\e[1;31mBlade(error): $@\nBlade (error): Blade will exit...\e[m" >&2
+        echo -e "\033[1;31mBlade(error): $@\nBlade (error): Blade will exit...\033[m" >&2
     else
         echo -e "Blade(error): $@\nBlade (error): Blade will exit..." >&2
     fi
     exit 1
 }
 
-blade_path=''
+function _full_real_path()
+{
+    local o
+    local f
+    f="$1"
 
-if [ -L "$0" ]; then
-    blade_path=`readlink -f $0`
-else
-    blade_path=$0
+    if [ ! -L "$0" ]; then
+        echo $f
+        return 0
+    fi
+
+    if o=`readlink -f $f 2>/dev/null`; then
+        echo "$o";
+        return 0
+    fi
+
+    # BSD readlink doesn't support -f
+    if o=`readlink $f`; then
+        f="$o"
+    fi
+
+    echo $(cd $(dirname $f) && pwd)/$(basename $f)
+    return 0
+}
+
+blade_path=`_full_real_path $0`
+blade_dir=$(cd $(dirname $blade_path) && pwd)
+blade_file="$blade_dir/bootstrap.py"
+
+if [[ "$BLADE_AUTO_UPGRADE" != "no" ]]; then
+    # Auto update blade main program to latest version and run it
+    if svn_up_info=`svn up --trust-server-cert --non-interactive ${blade_dir} 2>&1`; then
+        _info "Auto upgrade success: $svn_up_info"
+    else
+        _warning "Auto upgrade failure: $svn_up_info"
+        _warning "Please svn up $blade_dir"
+        _warning "You can setenv BLADE_AUTO_UPGRADE=no to disable auto upgrade"
+    fi
 fi
 
-blade_dir=$(cd $(dirname $blade_path) && pwd)
-
-blade_file="$blade_dir/blade.zip"
-
 # Check the python version at first, exit blade when python
-# version is under 2.6
+# version is under 2.4
 no_python=$(which python 2>&1 | grep 'which: no')
 if [[ -n "$no_python" ]]; then
-    _error_exit "Please install python 2.6 or above in your system"
+    _error_exit "Please install python 2.4 or above in your system"
 fi
 
 python_ver=$(python -V 2>&1 | sed 's/Python //g')
 
-if [[ "$python_ver" < "2.6" ]]; then
+if [[ "$python_ver" < "2.4" ]]; then
     _info "Python version in your machine: $python_ver"
-    _error_exit "Please upgrade your python version to 2.6 or above"
+    _error_exit "Please upgrade your python version to 2.4 or above"
 fi
 
 # Check scons environment
@@ -76,11 +105,9 @@ if [[ -n "$no_scons" ]]; then
     _error_exit "Please install scons v2.0 or above on your machine"
 fi
 
-# blade now
+# Check blade.zip
 if [[ ! -f "$blade_file" ]]; then
     _error_exit "Cannot find the core file $blade_file"
 fi
 
-
-echo python $blade_file "$@"
 python $blade_file "$@"
